Repository johnsonandjohnson/Bodiless-JS, pull requests merged in 2020-03, with the labels that each got.

#198 fix(layouts): Fix/no link in flexbox
  packages/bodiless-layouts/src/FlexboxGrid/EditFlexbox.tsx
  packages/bodiless-layouts/src/FlexboxGrid/SortableContainer.tsx
Labels: bug

#206 feat(organisms): Element selector enhancement for Single Accordion
  examples/test-site/src/components/SingleAccordion/index.tsx
  examples/test-site/src/data/pages/accordion/index.tsx
  packages/bodiless-organisms/__tests__/SingleAccordion.test.tsx
  packages/bodiless-organisms/src/components/SingleAccordion.tsx
  packages/bodiless-organisms/src/index.ts
Labels: testing enhancement

#181 test(organisms):smoke test for single accordion
  cypress/integration/smokeTest/singleAccordion_spec.js
  cypress/integration/smokeTest/touts_spec.js
Labels: testing enhancement

#147 docs(bodiless-documentation): Design Elements Basics tutorial
  packages/bodiless-documentation/doc/About/DesignElementBasics.md
  packages/bodiless-documentation/doc/About/SiteBuildBasics.md
  packages/bodiless-documentation/doc/Design/DesignSystem.md
  packages/fclasses/README.md
Labels: documentation
