Repository johnsonandjohnson/Bodiless-JS, pull requests merged in 2020-04, with the labels that each got.

#184 test(organisms):add smoke tests for Link Toggle
  cypress/integration/smokeTest/linkToggle_spec.js
Labels: testing enhancement

#128 docs(bodiless-documentation): Add required NPM version
  packages/bodiless-documentation/doc/About/GettingStarted.md
  packages/bodiless-documentation/doc/README.md
Labels: documentation

#143 docs(bodiless-documentation): Fix migration documentation
  packages/bodiless-documentation/doc/Development/Architecture/Documentation.md
  packages/bodiless-documentation/doc/Development/OtherResources/Lessons.md
  packages/bodiless-documentation/doc/Development/OtherResources/Windows.md
  packages/bodiless-migration-tool/doc/Technical/MigrationTool.md
  packages/bodiless-psh/README.md
Labels: documentation

#118 feat(layout): Rename Flexbox to FlowContainer
  examples/test-site/src/components/FlowContainer/Categories.ts
  examples/test-site/src/components/FlowContainer/index.tsx
  examples/test-site/src/components/FlowContainer/token.tsx
  examples/test-site/src/components/FlowContainer/withContentfulTouts.tsx
  examples/test-site/src/components/FlowContainer/withRichTextVariations.tsx
  examples/test-site/src/components/FlowContainer/withSingleAccordionVariations.tsx
  examples/test-site/src/components/FlowContainer/withToutVariations.tsx
  examples/test-site/src/components/ProductListing/ProductListingFlowContainer.tsx
  examples/test-site/src/components/ProductListing/index.tsx
  examples/test-site/src/data/pages/flow-container/index.tsx
  examples/test-site/src/data/pages/gallery-final/Gallery.tsx
  examples/test-site/src/data/pages/index.tsx
  examples/test-site/src/data/pages/richtext/index.tsx
  examples/test-site/src/templates/_default.jsx
  examples/test-site/src/templates/product_detail.jsx
  examples/test-site/src/templates/product_listing.jsx
  packages/bodiless-documentation/doc/About/DesignElementBasics.md
  packages/bodiless-documentation/doc/About/SiteBuildBasics.md
  packages/bodiless-layouts-ui/README.md
  packages/bodiless-layouts-ui/src/ComponentSelector.tsx
  packages/bodiless-layouts-ui/src/FlowContainer.tsx
  packages/bodiless-layouts-ui/src/index.ts
  packages/bodiless-layouts/README.md
  packages/bodiless-layouts/__tests__/ComponentSelector/componentSelectorForm.test.tsx
  packages/bodiless-layouts/__tests__/FlexboxGrid/model.test.ts
  packages/bodiless-layouts/__tests__/FlexboxGrid/useGetMenuOptions.test.tsx
  packages/bodiless-layouts/bodiless.docs.json
  packages/bodiless-layouts/src/ComponentSelector/componentSelectorForm.tsx
  packages/bodiless-layouts/src/ComponentSelector/types.tsx
  packages/bodiless-layouts/src/ComponentSelector/uiContext.tsx
  packages/bodiless-layouts/src/FlexboxGrid/__mocks__/model.ts
  packages/bodiless-layouts/src/FlowContainer/EditFlowContainer.tsx
  packages/bodiless-layouts/src/FlowContainer/SortableChild.tsx
  packages/bodiless-layouts/src/FlowContainer/SortableContainer.tsx
  packages/bodiless-layouts/src/FlowContainer/StaticFlowContainer.tsx
  packages/bodiless-layouts/src/FlowContainer/__mocks__/model.ts
  packages/bodiless-layouts/src/FlowContainer/index.tsx
  packages/bodiless-layouts/src/FlowContainer/model.ts
  packages/bodiless-layouts/src/FlowContainer/types.ts
  packages/bodiless-layouts/src/FlowContainer/useGetMenuOptions.tsx
  packages/bodiless-layouts/src/FlowContainer/utils/appendTailwindWidthClass.ts
  packages/bodiless-layouts/src/SortableResizableWrapper/index.tsx
  packages/bodiless-layouts/src/index.ts
Labels: help wanted

#273 Feat(organisms) Carousel Image Only
  examples/test-site/src/components/Carousel/index.tsx
  examples/test-site/src/components/Carousel/token.ts
  examples/test-site/src/data/pages/carousel/autorotating$slides$051fd72d-68a7-4ad0-b516-a712925bc9cb$image.json
  examples/test-site/src/data/pages/carousel/autorotating$slides$131fd088-58b8-4ee2-8fc4-8e9f6c2cbd9a$image.json
  examples/test-site/src/data/pages/carousel/autorotating$slides$default$image.json
  examples/test-site/src/data/pages/carousel/autorotating$slides.json
  examples/test-site/src/data/pages/carousel/index.tsx
  examples/test-site/src/data/pages/carousel/nonrotating$slides$2b71f3fe-445d-417f-8386-658a9a022a5a$image.json
  examples/test-site/src/data/pages/carousel/nonrotating$slides$d06370d4-ab7d-4fbd-a053-4ed832186727$image.json
  examples/test-site/src/data/pages/carousel/nonrotating$slides$default$image.json
  examples/test-site/src/data/pages/carousel/nonrotating$slides.json
  examples/test-site/static/images/1280x300.jpg
  examples/test-site/static/images/1280x300blue.jpg
  examples/test-site/static/images/1280x300green.jpg
  packages/bodiless-components/src/Image.tsx
  packages/bodiless-migration-tool/examples/settings/to_components.json
  packages/bodiless-organisms/README.md
  packages/bodiless-organisms/bodiless.docs.json
  packages/bodiless-organisms/doc/BurgerMenu.md
  packages/bodiless-organisms/doc/Carousel.md
  packages/bodiless-organisms/doc/MainMenu.md
  packages/bodiless-organisms/doc/SingleAccordion.md
  packages/bodiless-organisms/src/components/Carousel.tsx
  packages/bodiless-organisms/src/components/Slider.tsx
  packages/bodiless-organisms/src/index.ts
Labels: help wanted

#286 docs(bodiless-psh): Update CDN doc
  packages/bodiless-psh/README.md
Labels: documentation
