Repository johnsonandjohnson/Bodiless-JS, pull requests merged in 2023-06, with the labels that each got.

#2100 feat(component scaffold): Component Scaffolder
  package-lock.json
  packages/__vital__/package.json
  packages/bodiless-scaffold/CHANGELOG.md
  packages/bodiless-scaffold/LICENSE
  packages/bodiless-scaffold/README.md
  packages/bodiless-scaffold/bin/scaffold.js
  packages/bodiless-scaffold/package.json
  packages/bodiless-scaffold/src/config/component.ts
  packages/bodiless-scaffold/src/config/component/actions.ts
  packages/bodiless-scaffold/src/config/component/index.ts
  packages/bodiless-scaffold/src/config/component/prompts.ts
  packages/bodiless-scaffold/src/config/component/validator.ts
  packages/bodiless-scaffold/src/config/package/.gitkeep
  packages/bodiless-scaffold/src/config/site/.gitkeep
  packages/bodiless-scaffold/src/index.ts
  packages/bodiless-scaffold/src/templates/component/Clean.tsx.hbs
  packages/bodiless-scaffold/src/templates/component/index.base.ts.hbs
  packages/bodiless-scaffold/src/templates/component/index.bl-edit.ts.hbs
  packages/bodiless-scaffold/src/templates/component/index.root.ts.hbs
  packages/bodiless-scaffold/src/templates/component/index.static.ts.hbs
  packages/bodiless-scaffold/src/templates/component/index.ts.hbs
  packages/bodiless-scaffold/src/templates/component/tests/Component.test.tsx.hbs
  packages/bodiless-scaffold/src/templates/component/tokens/index.ts.hbs
  packages/bodiless-scaffold/src/templates/component/tokens/libraryComponent.ts.hbs
  packages/bodiless-scaffold/src/templates/component/types.ts.hbs
  packages/bodiless-scaffold/src/templates/shadow/component.ts.hbs
  packages/bodiless-scaffold/tsconfig.json
Labels: documentation

#2113 fix(package-lock): Restore broken lock file
  package-lock.json
Labels: ready-to-test

#2116 fix(docs): fixing page build cycle
  packages/bodiless-documentation/src/defaultToc.ts
Labels: skip-tests

#2118 docs(bodiless-documentation): Add Shadowing Tutorial
  packages/bodiless-documentation/doc/Development/Guides/BuildingSites/Typography/ShadowGuide.md
  packages/bodiless-documentation/src/defaultToc.ts
  packages/vital-buttons/doc/README.md
  packages/vital-card/doc/README.md
  packages/vital-editors/doc/PlainEditor.md
  packages/vital-editors/doc/RichText.md
  packages/vital-elements/bodiless.docs.json
  packages/vital-elements/doc/ComponentTemplate.md
  packages/vital-elements/doc/Shadow.md
  packages/vital-elements/doc/SiteTypography.md
  packages/vital-elements/doc/VitalElements.md
  packages/vital-examples/bodiless.docs.json
  packages/vital-examples/doc/Guides/ShadowingTokens.md
  packages/vital-examples/doc/Introduction/CoreConcepts.md
  packages/vital-flowcontainer/doc/FlowContainer.md
  packages/vital-image/doc/README.md
  packages/vital-layout/doc/Footer.md
  packages/vital-layout/doc/Header.md
  packages/vital-layout/doc/Helmet.md
  packages/vital-layout/doc/Layout.md
  packages/vital-layout/doc/Logo.md
  packages/vital-list/doc/README.md
  packages/vital-meta/doc/SEO.md
  packages/vital-meta/doc/ShadowingMeta.md
  packages/vital-meta/doc/Share.md
  packages/vital-section/doc/README.md
  packages/vital-table/doc/README.md
  packages/vital-templates/doc/Generic.md
Labels: documentation, skip-tests

#2119 docs(vital-examples): Update order of Curriculum Lessons
  packages/vital-examples/bodiless.docs.json
Labels: documentation, skip-tests

#2120 docs(bodiless-documentation): Fix endless cycle
  packages/bodiless-documentation/src/defaultToc.ts
Labels: documentation, skip-tests

#2121 fix(package-lock): Fixing broken lock file
  package-lock.json
Labels: skip-tests

#2123 fix(package-lock): Fixing broken lock file
  package-lock.json
Labels: skip-tests

#2136 fix: Page order in Docsify
  packages/bodiless-documentation/src/tree.ts
  packages/bodiless-ga4/bodiless.docs.json
  packages/bodiless-organisms/bodiless.docs.json
  packages/vital-editors/bodiless.docs.json
  packages/vital-elements/bodiless.docs.json
  packages/vital-examples/bodiless.docs.json
  packages/vital-layout/bodiless.docs.json
Labels: bug, documentation
